[workspace]
members = [
    "app",
    "arch",
    "devices/stm32f429zi",
    "devices/wio_terminal",
    "kernel",
    "log",
    "qemu_app",
    "rt",
    "user",
    "util",
    "wio_app",
]
exclude = [".cargo"]
