[package]
name = "util"
version = "0.1.0"
authors = ["garasubo <garasubo@gmail.com>"]
edition = "2018"

[dev-dependencies]
rand = "0.3"

[dependencies]
array-init = "2.0"
lock_api = { version = "0.4", features = ["nightly"] }

[features]
alloc = []

