[package]
name = "stm32f429zi"
version = "0.1.0"
authors = ["garasubo <garasubo@gmail.com>"]
edition = "2018"

[dependencies]
vcell = "0.1.0"
embedded-hal = "0.2.2"
nb = "0.1.2"
rt = { path = "../../rt" }
volatile-register = "0.2.0"
aligned = "0.3.2"
